// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-XI4-ezErH9e0GbUqA8cjND09MSR0ms',
    appId: '1:215953934792:web:99d854936c1af24d0c58fd',
    messagingSenderId: '215953934792',
    projectId: 'importaya-ia-platform',
    authDomain: 'importaya-ia-platform.firebaseapp.com',
    storageBucket: 'importaya-ia-platform.firebasestorage.app',
    measurementId: 'G-R1ZCXPP50G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeWj2IcirXz3VsmsnkAyAo_IUst77bN9I',
    appId: '1:215953934792:android:c42a1bc169f734650c58fd',
    messagingSenderId: '215953934792',
    projectId: 'importaya-ia-platform',
    storageBucket: 'importaya-ia-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6EHS1UuI4yc3OIIOl9YHY6kToeozzhiE',
    appId: '1:215953934792:ios:669a6b4bad0fdea50c58fd',
    messagingSenderId: '215953934792',
    projectId: 'importaya-ia-platform',
    storageBucket: 'importaya-ia-platform.firebasestorage.app',
    iosBundleId: 'com.example.pruebaPytoflutterImportayaia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw-XI4-ezErH9e0GbUqA8cjND09MSR0ms',
    appId: '1:215953934792:web:16366fab13f911f60c58fd',
    messagingSenderId: '215953934792',
    projectId: 'importaya-ia-platform',
    authDomain: 'importaya-ia-platform.firebaseapp.com',
    storageBucket: 'importaya-ia-platform.firebasestorage.app',
    measurementId: 'G-CZP4W04H5D',
  );

}